name: "Check cherry-picks"
on:
  pull_request_target:
    branches:
     - 'release-**'
     - 'staging-**'
     - '!staging-next'

permissions:
  checks: write

jobs:
  check:
    name: cherry-pick-check
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'NixOS'
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        filter: blob:none
    - name: Check cherry-picks
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_API_URL: https://api.github.com/repos/${{ github.repository }}
        SELF_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        ./maintainers/scripts/check-cherry-picks.sh "$BASE_SHA" "$HEAD_SHA"
