name: Check GitHub Actions with zizmor

on:
  push:
    branches: ["master", "release-**", "staging-**"]
  pull_request:
    branches: ["master", "release-**", "staging-**"]

jobs:
  zizmor:
    name: zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # v31.1.0

      - name: Run zizmor 🌈
        run: |
          nix-build ci -A pkgs.zizmor
          ./result/bin/zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
        with:
          sarif_file: results.sarif
          category: zizmor
